1.Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np

In [10]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[10,11,12],[13,14,15],[16,17,18]])
result=A+B

In [11]:
print(result)

[[11 13 15]
 [17 19 21]
 [23 25 27]]


2.Write a Python Program to Multiply Two Matrices?

In [12]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[10,11,12],[13,14,15],[16,17,18]])
result=a@b
print(result)

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


3. Write a Python Program to Transpose a Matrix?

In [25]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
result=a.T

In [26]:
result

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [27]:
# alternate method
result=np.transpose(a)

In [28]:
result

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

4. Write a Python Program to Sort Words in Alphabetic Order?

In [29]:
words=input("Enter a list of words separated by spaces: ").split()
words.sort()
print("Sorted words: ")
for i in words:
    print(i)

Enter a list of words separated by spaces: hello my name is simal
Sorted words: 
hello
is
my
name
simal


5. Write a Python Program to Remove Punctuation From a String?

In [42]:
import re
sentance=input()
result=re.sub(r'[^\w\s]',"",sentance)
print(result)

"hello ! my name ' is ? simal"
hello  my name  is  simal
